/**
 * Auto-generated Tool Registry
 * Generated at: 2026-01-01T03:17:24.482Z
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * Run 'npm run generate-tools' to regenerate
 */

import { APIGatewayTool } from '../apigateway/APIGatewayTool';
import { CloudFormationTool } from '../cloudformation/CloudFormationTool';
import { CloudWatchLogTool } from '../cloudwatch/CloudWatchLogTool';
import { FileOperationsTool } from '../common/FileOperationsTool';
import { SessionTool } from '../common/SessionTool';
import { DynamoDBTool } from '../dynamodb/DynamoDBTool';
import { EC2Tool } from '../ec2/EC2Tool';
import { EMRTool } from '../emr/EMRTool';
import { GlueTool } from '../glue/GlueTool';
import { IAMTool } from '../iam/IAMTool';
import { LambdaTool } from '../lambda/LambdaTool';
import { RDSTool } from '../rds/RDSTool';
import { RDSDataTool } from '../rdsdata/RDSDataTool';
import { S3FileOperationsTool } from '../s3/S3FileOperationsTool';
import { S3Tool } from '../s3/S3Tool';
import { SNSTool } from '../sns/SNSTool';
import { SQSTool } from '../sqs/SQSTool';
import { StepFuncTool } from '../stepfunc/StepFuncTool';
import { STSTool } from '../sts/STSTool';
import { TestAwsConnectionTool } from '../sts/TestAwsConnectionTool';

export interface ToolRegistryEntry {
  name: string;
  instance: any;
}

/**
 * Tools for VS Code Language Model API registration
 */
export const EXTENSION_TOOLS: ToolRegistryEntry[] = [
  { name: 'APIGatewayTool', instance: new APIGatewayTool() },
  { name: 'CloudFormationTool', instance: new CloudFormationTool() },
  { name: 'CloudWatchLogTool', instance: new CloudWatchLogTool() },
  { name: 'FileOperationsTool', instance: new FileOperationsTool() },
  { name: 'SessionTool', instance: new SessionTool() },
  { name: 'DynamoDBTool', instance: new DynamoDBTool() },
  { name: 'EC2Tool', instance: new EC2Tool() },
  { name: 'EMRTool', instance: new EMRTool() },
  { name: 'GlueTool', instance: new GlueTool() },
  { name: 'IAMTool', instance: new IAMTool() },
  { name: 'LambdaTool', instance: new LambdaTool() },
  { name: 'RDSTool', instance: new RDSTool() },
  { name: 'RDSDataTool', instance: new RDSDataTool() },
  { name: 'S3FileOperationsTool', instance: new S3FileOperationsTool() },
  { name: 'S3Tool', instance: new S3Tool() },
  { name: 'SNSTool', instance: new SNSTool() },
  { name: 'SQSTool', instance: new SQSTool() },
  { name: 'StepFuncTool', instance: new StepFuncTool() },
  { name: 'STSTool', instance: new STSTool() },
  { name: 'TestAwsConnectionTool', instance: new TestAwsConnectionTool() }
];

/**
 * Tools for MCP (Model Context Protocol) bridge
 */
export const MCP_TOOLS: ToolRegistryEntry[] = [
  { name: 'APIGatewayTool', instance: new APIGatewayTool() as any },
  { name: 'CloudFormationTool', instance: new CloudFormationTool() as any },
  { name: 'CloudWatchLogTool', instance: new CloudWatchLogTool() as any },
  { name: 'FileOperationsTool', instance: new FileOperationsTool() as any },
  { name: 'SessionTool', instance: new SessionTool() as any },
  { name: 'DynamoDBTool', instance: new DynamoDBTool() as any },
  { name: 'EC2Tool', instance: new EC2Tool() as any },
  { name: 'EMRTool', instance: new EMRTool() as any },
  { name: 'GlueTool', instance: new GlueTool() as any },
  { name: 'IAMTool', instance: new IAMTool() as any },
  { name: 'LambdaTool', instance: new LambdaTool() as any },
  { name: 'RDSTool', instance: new RDSTool() as any },
  { name: 'RDSDataTool', instance: new RDSDataTool() as any },
  { name: 'S3FileOperationsTool', instance: new S3FileOperationsTool() as any },
  { name: 'S3Tool', instance: new S3Tool() as any },
  { name: 'SNSTool', instance: new SNSTool() as any },
  { name: 'SQSTool', instance: new SQSTool() as any },
  { name: 'StepFuncTool', instance: new StepFuncTool() as any },
  { name: 'STSTool', instance: new STSTool() as any },
  { name: 'TestAwsConnectionTool', instance: new TestAwsConnectionTool() as any }
];

/**
 * Get tool metadata from schemas
 */
export async function getToolMetadata(toolName: string): Promise<any> {
  const manifest = require('./toolManifest.json');
  const tool = manifest.tools.find((t: any) => t.name === toolName);
  
  if (!tool) {
    throw new Error(`Tool not found: ${toolName}`);
  }
  
  const schemaPath = require('path').join(__dirname, tool.schemaPath);
  return require(schemaPath);
}

/**
 * Get all tool metadata
 */
export async function getAllToolMetadata(): Promise<any[]> {
  const manifest = require('./toolManifest.json');
  return Promise.all(
    manifest.tools.map((t: any) => {
      const schemaPath = require('path').join(__dirname, t.schemaPath);
      return require(schemaPath);
    })
  );
}
